import { Link } from 'react-router-dom';
import { Breadcrumbs } from '../components/Breadcrumbs';
import { ReviewBadge } from '../components/Cards';

function TrustLayout({ label, title, intro, children }: { label: string; title: string; intro: string; children: React.ReactNode }) {
  return <main id="main-content"><div className="wrap narrow"><Breadcrumbs items={[{ label: title }]} /><header className="page-header"><span className="eyebrow">{label}</span><h1>{title}</h1><p>{intro}</p></header><div className="prose">{children}</div></div></main>;
}

export function AboutPage() {
  return <TrustLayout label="Über das Portal" title="Wissen erklären. Grenzen sichtbar machen." intro="MPUdeincoach Wissen ist das Wissensportal rund um die MPU."><h2>Eine Marke, zwei Aufgaben</h2><p>Beide Domains gehören zur Marke MPUdeincoach. Dieses Portal beantwortet allgemeine Informationsfragen. Die kommerzielle Website <a href="https://mpudeincoach.de">mpudeincoach.de</a> ist für Fallanalyse, Beratung, Vorbereitung, Angebote und Produkte zuständig. Inhalte werden nicht zwischen beiden Domains umgeschrieben oder dupliziert.</p><h2>Redaktion statt Behauptung</h2><p>Artikel erhalten strukturierte Metadaten, Quellen, Status, Prüfdatum und einen Korrekturweg. Rechtliche, medizinische und verfahrensbezogene Aussagen werden nur mit geeigneter Quelle und fachlicher Prüfung indexierbar.</p><h2>Wer steht hinter den Texten?</h2><p>Die aktuelle technische Arbeitsfassung wird von der „Redaktion MPU Wissen“ geführt. Eine reale Autor- und Reviewer-Zuordnung wird erst nach dokumentierter Freigabe veröffentlicht; Namen oder Qualifikationen werden nicht erfunden.</p><ReviewBadge /><p><Link to="/redaktion/">Mehr über Rollen und Freigaben →</Link></p></TrustLayout>;
}

export function EditorialPage() {
  return <TrustLayout label="Verantwortung" title="Redaktion und Fachprüfung" intro="Jeder Inhalt hat eine dokumentierte Rolle, einen Status und einen klaren Freigabeweg."><h2>Redaktionelle Rolle</h2><p>Die Redaktion legt Thema und Domain-Eigentum fest, formuliert verständlich, ordnet Quellen zu und dokumentiert Änderungen. Sie erteilt keine rechtliche, medizinische oder psychologische Fachfreigabe.</p><h2>Fachliche und rechtliche Rollen</h2><p>Der fachliche Reviewer prüft die ihm zugewiesenen MPU-, verkehrspsychologischen oder CTU-Aussagen. Der rechtliche Reviewer prüft Rechtsgrundlagen und verfahrensbezogene Auslegung. Eine redaktionelle Prüfung ersetzt keine dieser Rollen.</p><h2>Dokumentierte Freigabe</h2><p>Reviewpflichtige Artikel bleiben bis zur tatsächlichen Freigabe noindex und außerhalb der Sitemap. Name, Rolle, Qualifikation, Datum, Umfang und nächste Prüfung werden erst nach einer belegten Zustimmung veröffentlicht. Derzeit liegt für die gekennzeichneten Arbeitsfassungen keine namentliche Fachfreigabe vor.</p></TrustLayout>;
}

export function EditorialPolicyPage() {
  return <TrustLayout label="Qualitätsstandard" title="Redaktionsrichtlinien" intro="Unsere Regeln zeigen, wie Aussagen entstehen, geprüft werden und eine Veröffentlichungsfreigabe erhalten."><h2>Von der Arbeitsfassung zur Freigabe</h2><ul><li>Primärthema, Suchintention und Domain-Eigentümer festlegen</li><li>eigenständigen Nutzwert und konkurrierende Seite dokumentieren</li><li>materiale Aussagen mit Quellen und Risikoklasse erfassen</li><li>passende redaktionelle, fachliche und rechtliche Rollen zuweisen</li><li>Korrekturen und Freigabeumfang dokumentieren</li><li>erst aus dem Freigabestatus Indexierbarkeit, Sitemap und Schema ableiten</li></ul><h2>Quellenhierarchie</h2><p>Gesetze und Behörden stehen vor offizieller Fachleitlinie, institutioneller Fachquelle und sekundärer Erklärung. Legacy-Texte und interne Notizen sind nur Arbeitshinweise und tragen Hochrisiko-Aussagen nie allein.</p><h2>Sensible Themen</h2><p>Fristen, Behördenverfahren, Abstinenz, Laborwerte, Cannabisrecht, Diagnosen und konkrete Fallstrategien bleiben bis zur geeigneten menschlichen Prüfung reviewpflichtig. Es gibt keine Bestehensgarantien.</p><h2>Prüf- und Aktualisierungsdaten</h2><p>Ein redaktionelles Änderungsdatum ist keine Fachfreigabe. Ein „zuletzt geprüft“- oder nächstes Prüfdatum wird nur mit dokumentiertem Reviewer, Umfang und Datum verwendet. Gesetzesänderungen, neue Fachstandards oder belegte Fehler lösen eine erneute Prüfung aus.</p><h2>Grenzen und KI-Unterstützung</h2><p>Das Portal bietet allgemeine Information und keine Einzelfall-, Rechts- oder Erfolgsberatung. Werkzeuge dürfen Recherche, Struktur und Sprachbearbeitung unterstützen; redaktionelle Verantwortung, Quellenprüfung und Fachfreigabe bleiben menschliche Aufgaben.</p></TrustLayout>;
}

export function CorrectionsPage() {
  return <TrustLayout label="Transparenz" title="Korrekturen und Hinweise" intro="Sachliche Fehler sollen schnell, nachvollziehbar und ohne künstliche Aktualisierung korrigiert werden."><h2>So meldest du einen Hinweis</h2><p>Der produktive Kontaktkanal ist noch nicht freigegeben. Bis zur Benennung einer verantwortlichen Redaktion werden keine Formulare oder alten WordPress-Endpunkte übernommen.</p><h2>Was wir für eine Prüfung brauchen</h2><ul><li>URL und betroffene Passage</li><li>kurze Beschreibung des möglichen Fehlers</li><li>wenn vorhanden: aktuelle Primärquelle</li><li>keine sensiblen Fallakten oder Gesundheitsdaten</li></ul><h2>Prüfung und Eskalation</h2><p>Die Redaktion prüft Quelle und Tragweite. Fachliche oder rechtliche Änderungen gehen erneut an die zuständige Reviewrolle; bis dahin bleibt betroffener Risikoinhalt noindex oder wird zurückgezogen.</p><h2>Korrekturprotokoll</h2><p>Materiale Korrekturen werden nach Einführung des produktiven Prozesses mit Datum, Art der Änderung, Quelle und Prüfrolle dokumentiert. Eine bloße Textänderung erzeugt kein neues Fachprüfdatum. Es liegen noch keine veröffentlichten Korrekturen vor.</p></TrustLayout>;
}

export function LegalPlaceholderPage({ kind }: { kind: 'Impressum' | 'Datenschutz' | 'AGB' }) {
  return <TrustLayout label="Rechtlicher Inhalt – noindex" title={kind} intro="Dieser rechtliche Inhalt ist noch nicht durch den verantwortlichen Betreiber freigegeben."><div className="legal-warning"><strong>Nicht veröffentlichungsbereit</strong><p>Alte WordPress-Rechtstexte wurden bewusst nicht übernommen. Betreiberangaben, Datenschutzverarbeitung und gegebenenfalls die Notwendigkeit von AGB müssen durch die zuständige Stelle neu freigegeben werden.</p></div></TrustLayout>;
}
