import { EDITORIAL_TEAM } from '../config/site';
import type { Article } from './model';
import { SOURCES } from './sources';

const common = {
  author: EDITORIAL_TEAM,
  reviewer: null,
  reviewScope: 'Fachliche und gegebenenfalls rechtliche Prüfung vor Indexfreigabe erforderlich.',
  reviewRequirements: ['MPU_FACHREVIEW', 'EDITORIAL_REVIEW', 'SOURCE_VERIFICATION'] as Article['reviewRequirements'],
  updatedAt: '2026-09-03',
  publicationState: 'FACHREVIEW_REQUIRED' as const,
  schema: ['Article', 'BreadcrumbList'] as Article['schema'],
};

export const ARTICLES: Article[] = [
  {
    ...common,
    id: 'mpu-ablauf',
    title: 'MPU-Verfahren: Rollen, Akte und Gutachten',
    slug: '/mpu-ablauf/',
    excerpt: 'Welche Rolle Behörde, Begutachtungsstelle, Unterlagen und Gutachten im Verfahren haben.',
    primaryTopic: 'MPU Ablauf',
    searchIntent: 'institutional roles and document flow',
    ownerDomain: 'SHARED_WITH_DIFFERENT_INTENT',
    competingExistingPage: 'https://mpudeincoach.de/mpu-ablauf (kommerzieller Ablauf- und Vorbereitungskontext)',
    uniqueValue: 'Der Wissenshub erklärt institutionelle Rollen, Aktenfluss und Verfahrensgrenzen statt eines kommerziellen Vorbereitungspfads.',
    pillar: 'MPU Ablauf',
    pillarSlug: '/wissen/',
    sources: [SOURCES.fev11, SOURCES.fev4a, SOURCES.bk5Foundations],
    reviewRequirements: ['MPU_FACHREVIEW', 'LEGAL_REVIEW', 'EDITORIAL_REVIEW', 'SOURCE_VERIFICATION'],
    reviewScope: 'Fachliche und rechtliche Prüfung der korrigierten Fassung abgeschlossen; keine universellen Untersuchungsbestandteile, Dauern oder Erfolgsaussagen.',
    publicationState: 'APPROVED_PUBLIC',
    schema: ['Article', 'BreadcrumbList', 'FAQPage'],
    body: [
      { type: 'paragraph', text: 'Das MPU-Verfahren verbindet mehrere Beteiligte mit unterschiedlichen Aufgaben. Diese Übersicht ordnet Behörde, betroffene Person, Begutachtungsstelle, Unterlagen und Gutachten ein. Sie ist kein persönlicher Vorbereitungs- oder Terminplan.' },
      { type: 'important', title: 'Wichtig', text: 'Fristen stehen im behördlichen Schreiben. Verlasse dich bei Fristfragen nicht auf allgemeine Internetangaben, sondern kläre dein eigenes Schreiben rechtzeitig mit der zuständigen Stelle oder fachkundiger rechtlicher Beratung.' },
      { type: 'heading', id: 'behoerde', title: 'Rolle der Fahrerlaubnisbehörde' },
      { type: 'paragraph', text: 'Die Fahrerlaubnisbehörde legt fest, welche Eignungsfrage durch ein Gutachten geklärt werden soll. Diese Fragestellung begrenzt den fachlichen Rahmen der Untersuchung. Sie ist deshalb ein zentraler Ausgangspunkt für die weitere Orientierung.' },
      { type: 'list', items: ['Schreiben und genannte Frist vollständig lesen', 'Fragestellung wörtlich festhalten', 'Hinweise auf einzureichende Unterlagen markieren', 'Unklare rechtliche Folgen nicht selbst interpretieren'] },
      { type: 'heading', id: 'stelle', title: 'Beauftragung und Aktenübermittlung' },
      { type: 'paragraph', text: 'Die Untersuchung findet bei einer amtlich anerkannten Begutachtungsstelle für Fahreignung statt. Nach § 11 Absatz 6 FeV teilt die betroffene Person der Behörde mit, welche in Betracht kommende Stelle beauftragt wurde; anschließend übermittelt die Behörde die verwendbaren Unterlagen und ihre Fragestellung.' },
      { type: 'heading', id: 'untersuchung', title: 'Aufgabe der Untersuchung' },
      { type: 'paragraph', text: 'Welche medizinischen, psychologischen oder leistungsbezogenen Befunde erhoben werden, hängt von der behördlichen Fragestellung und den anwendbaren Begutachtungsgrundsätzen ab. Die FeV verlangt eine anlassbezogene Untersuchung nach anerkannten wissenschaftlichen Grundsätzen.' },
      { type: 'heading', id: 'gutachten', title: 'Gutachten und Verfahrensgrenze' },
      { type: 'paragraph', text: 'Das Gutachten beantwortet die behördliche Fragestellung. Welche Konsequenzen sich daraus im Einzelfall ergeben und wie mit einem Ergebnis umzugehen ist, ist eine rechtlich und fachlich sensible Frage. Diese Seite ersetzt keine Einzelfallprüfung.' },
    ],
    faq: [
      { question: 'Wie lange dauert der gesamte MPU-Ablauf?', answer: 'Eine pauschale Dauer ist nicht seriös: Behördliche Fristen, Aktenversand, Terminverfügbarkeit, gegebenenfalls erforderliche Nachweise und die individuelle Vorbereitung unterscheiden sich.', publicationState: 'PUBLIC_APPROVED' },
      { question: 'Besteht jede MPU aus denselben Teilen?', answer: 'Nein. Welche medizinischen, psychologischen oder leistungsbezogenen Befunde erhoben werden, hängt von der behördlichen Fragestellung und den anwendbaren Begutachtungsgrundsätzen ab.', publicationState: 'PUBLIC_APPROVED' },
    ],
    relatedArticles: ['/mpu-begutachtungsstelle/', '/abstinenznachweis/', '/faq/'],
    ctaTarget: 'FALLANALYSE',
    metaTitle: 'MPU-Verfahren: Rollen und Aktenfluss | MPU Wissen',
    metaDescription: 'MPU-Verfahren neutral erklärt: Rollen von Behörde und Begutachtungsstelle, Aktenübermittlung, Untersuchung und Gutachten.',
    canonical: 'https://mpu-deincoach.de/mpu-ablauf/',
  },
  {
    ...common,
    id: 'mpu-kosten',
    title: 'MPU-Kosten: Bestandteile und Einflussfaktoren',
    slug: '/mpu-kosten/',
    excerpt: 'Welche Kostenblöcke vorkommen können und warum ein einziger Pauschalbetrag häufig in die Irre führt.',
    primaryTopic: 'MPU Kosten',
    searchIntent: 'neutral fee taxonomy and source currency',
    ownerDomain: 'SHARED_WITH_DIFFERENT_INTENT',
    competingExistingPage: 'https://mpudeincoach.de/mpu-kosten (Service- und Vorbereitungskosten)',
    uniqueValue: 'Neutrale Kostentaxonomie und Aktualitätsregeln ohne Paketpreise, Angebotsvergleich oder Verkaufsabsicht.',
    pillar: 'MPU Kosten',
    pillarSlug: '/wissen/',
    sources: [SOURCES.fev11, SOURCES.fev4a, SOURCES.bk5Foundations],
    reviewRequirements: ['MPU_FACHREVIEW', 'LEGAL_REVIEW', 'EDITORIAL_REVIEW', 'SOURCE_VERIFICATION'],
    reviewScope: 'Fach- und Quellenprüfung der Kostentaxonomie sowie rechtliche Prüfung verfahrensbezogener Kostenformulierungen vor Indexfreigabe erforderlich.',
    body: [
      { type: 'paragraph', text: 'Zu den Gesamtkosten rund um eine MPU können mehrere voneinander unabhängige Positionen gehören. Ein einzelner Betrag ohne Kontext sagt daher wenig aus. Aktuelle Preise müssen direkt bei den jeweils beauftragten Stellen geprüft werden.' },
      { type: 'heading', id: 'behoerde', title: 'Fahrerlaubnisbehörde und Verwaltungsverfahren' },
      { type: 'paragraph', text: 'Gebühren oder Auslagen des Fahrerlaubnisverfahrens sind von anderen Kostenblöcken zu trennen. Sie gelten nicht automatisch in gleicher Form für jeden Fall; vor einer Veröffentlichung konkreter Angaben ist eine aktuelle Primärquelle der zuständigen Stelle erforderlich.' },
      { type: 'heading', id: 'begutachtungsstelle', title: 'Begutachtungsstelle' },
      { type: 'paragraph', text: 'Das Entgelt der beauftragten Begutachtungsstelle ist ein eigener Kostenblock. Konkrete Beträge dürfen nur mit einer aktuellen Preis- oder Leistungsangabe der jeweiligen Stelle veröffentlicht werden.' },
      { type: 'heading', id: 'dolmetschen', title: 'Dolmetscher oder Übersetzer, falls erforderlich' },
      { type: 'paragraph', text: 'Anlage 4a FeV regelt, dass eine medizinisch-psychologische Untersuchung unter bestimmten Voraussetzungen mit einem von der Begutachtungsstelle bestellten Dolmetscher oder Übersetzer durchgeführt werden kann und die untersuchte Person die Kosten trägt. Dieser Block fällt nicht in jedem Fall an.' },
      { type: 'heading', id: 'vorbereitung', title: 'Frei gewählte private Vorbereitung' },
      { type: 'paragraph', text: 'Eine freiwillig gewählte private Vorbereitung ist von Behörde und Begutachtung zu trennen. Kostenangaben benötigen eine aktuelle Anbieterquelle und gelten nur für das tatsächlich gewählte Angebot.' },
      { type: 'heading', id: 'abstinenz', title: 'Abstinenz- oder Laborbelege, falls erforderlich' },
      { type: 'paragraph', text: 'Kosten für Abstinenz- oder Laborbelege sind nur relevant, wenn solche Belege im konkreten Fall benötigt werden. Allgemeine Beträge bleiben gesperrt, bis eine aktuelle Quelle der jeweiligen Untersuchungsstelle oder des Labors vorliegt.' },
      { type: 'heading', id: 'dokumente', title: 'Dokumentenbeschaffung, falls erforderlich' },
      { type: 'paragraph', text: 'Für die Beschaffung einzelner Unterlagen können im Einzelfall Kosten entstehen. Eine allgemeine Veröffentlichung setzt eine aktuelle Primär- oder Ausstellerquelle voraus.' },
      { type: 'heading', id: 'reise', title: 'Reise- und Nebenkosten' },
      { type: 'paragraph', text: 'Anreise, gegebenenfalls Übernachtung und weitere Nebenkosten hängen von der persönlichen Organisation ab und fallen nicht automatisch an. Sie sind keine pauschale MPU-Gebühr.' },
      { type: 'heading', id: 'aktualitaet', title: 'Quellen- und Aktualitätsregel' },
      { type: 'paragraph', text: 'Kostenpositionen und konkrete Beträge sind getrennt zu behandeln. Ein Betrag darf erst veröffentlicht werden, wenn Anbieter oder zuständige Stelle, Leistungsumfang, Währung und Prüfdatum dokumentiert sind.' },
      { type: 'callout', title: 'Keine Preisfreigabe', text: 'Diese Fassung veröffentlicht bewusst keine konkreten Preiszahlen. Zeitabhängige Beträge benötigen vor einer Veröffentlichung eine dokumentierte Quellen- und Aktualitätsprüfung.' },
    ],
    faq: [
      { question: 'Gibt es einen einheitlichen Preis für jede MPU?', answer: 'Die Kostenblöcke und ihre Anwendbarkeit unterscheiden sich je nach Verfahren und Fall. Aktuelle Beträge müssen bei der jeweils zuständigen Stelle geprüft werden.', publicationState: 'REVIEW_REQUIRED' },
      { question: 'Warum werden Kostenpositionen getrennt ausgewiesen?', answer: 'Behördenverfahren, Begutachtung, mögliche Nachweise und freiwillige Leistungen haben unterschiedliche Anbieter und Preisstände. Eine getrennte Taxonomie macht Quelle und Aktualität jeder Position prüfbar.', publicationState: 'REVIEW_REQUIRED' },
    ],
    relatedArticles: ['/mpu-ablauf/', '/abstinenznachweis/', '/mpu-begutachtungsstelle/'],
    ctaTarget: 'FALLANALYSE',
    metaTitle: 'MPU-Kosten: Bestandteile verstehen | MPU Wissen',
    metaDescription: 'MPU-Kosten neutral einordnen: Kostenblöcke, Quellen und Aktualitätsregeln ohne Paketvergleich oder veraltete Pauschalpreise.',
    canonical: 'https://mpu-deincoach.de/mpu-kosten/',
  },
  {
    ...common,
    id: 'alkohol-mpu',
    title: 'Alkohol-MPU: Grundlagen und Wissensübersicht',
    slug: '/alkohol-mpu/',
    excerpt: 'Eine fachliche Landkarte zu Anlass, Konsumgeschichte, Veränderung und Nachweisen.',
    primaryTopic: 'Alkohol MPU Wissen',
    searchIntent: 'alcohol risk, change and evidence concepts',
    ownerDomain: 'SHARED_WITH_DIFFERENT_INTENT',
    competingExistingPage: 'https://mpudeincoach.de/mpu-vorbereitung-alkohol (kommerzielle Vorbereitung)',
    uniqueValue: 'Begriffliche und fachliche Orientierung statt Fallanalyse, Angebot oder Erfolgsversprechen.',
    pillar: 'Alkohol MPU',
    pillarSlug: '/wissen/',
    sources: [SOURCES.bk5Alcohol, SOURCES.bk5Ctu, SOURCES.fev4a, SOURCES.bastGuidelines],
    body: [
      { type: 'paragraph', text: 'Bei einer Alkohol-MPU geht es nicht um eine isolierte Musterantwort. Fachlich betrachtet werden Anlass, Entwicklung des Konsums, persönliche Risikofaktoren, die Auseinandersetzung mit dem Verhalten und die Stabilität der Veränderung.' },
      { type: 'heading', id: 'konsumgeschichte', title: 'Die eigene Konsumgeschichte einordnen' },
      { type: 'paragraph', text: 'Wichtig ist eine zeitlich nachvollziehbare Darstellung: Wie hat sich der Konsum entwickelt, in welchen Situationen wurde getrunken und welche Folgen wurden lange unterschätzt? Eine ehrliche Rekonstruktion ist etwas anderes als eine nachträglich geglättete Geschichte.' },
      { type: 'heading', id: 'veraenderung', title: 'Veränderung muss zum früheren Risiko passen' },
      { type: 'paragraph', text: 'Tragfähige Veränderungen betreffen nicht nur den Alkoholkonsum selbst. Häufig gehören neue Entscheidungen, andere Routinen, ein veränderter Umgang mit Belastungen und ein konkreter Plan für Risikosituationen dazu.' },
      { type: 'heading', id: 'abstinenz', title: 'Abstinenz und fallbezogene Trennfähigkeit nicht pauschal entscheiden' },
      { type: 'important', title: 'Einzelfallprüfung', text: 'Anlage 4a FeV unterscheidet unter anderem Abhängigkeit und Alkoholmissbrauch: Bei vorausgegangener Abhängigkeit erstreckt sich die Untersuchung auf stabile Abstinenz; bei Alkoholmissbrauch ohne frühere oder aktuelle Abhängigkeit darauf, ob Alkoholkonsum und das Führen von Kraftfahrzeugen zuverlässig getrennt werden können. Welche Konstellation vorliegt, lässt sich nicht aus einem Einzelwert oder einer allgemeinen Internetregel ableiten. Weitergehende Aussagen bleiben bis zur aktuellen Fachquellenprüfung gesperrt.' },
      { type: 'heading', id: 'nachweise', title: 'Nachweise früh und passend klären' },
      { type: 'paragraph', text: 'Wenn Nachweise relevant sind, müssen Methode, Zeitraum und formale Qualität zum fachlichen Bedarf passen. Nachträglich lässt sich ein ungeeignetes oder lückenhaftes Vorgehen nicht immer korrigieren.' },
    ],
    faq: [
      { question: 'Braucht jede Alkohol-MPU einen Abstinenznachweis?', answer: 'Eine pauschale Aussage ist fachlich nicht vertretbar. Anlass, Konsummuster, Vorgeschichte, Veränderungsweg und Aktenlage müssen zusammen geprüft werden.', publicationState: 'REVIEW_REQUIRED' },
      { question: 'Reicht es, seit dem Vorfall weniger zu trinken?', answer: 'Eine bloße Behauptung reicht nicht. Entscheidend ist, ob die Veränderung nachvollziehbar, stabil und zum früheren Risiko passend aufgearbeitet wurde.', publicationState: 'REVIEW_REQUIRED' },
    ],
    relatedArticles: ['/abstinenznachweis/', '/mpu-ablauf/', '/faq/'],
    ctaTarget: 'ALKOHOL',
    metaTitle: 'Alkohol-MPU: Grundlagen verstehen | MPU Wissen',
    metaDescription: 'Alkohol-MPU verständlich einordnen: Konsumgeschichte, Veränderung, Risikoverständnis und Nachweise – ohne pauschale Versprechen.',
    canonical: 'https://mpu-deincoach.de/alkohol-mpu/',
  },
  {
    ...common,
    id: 'drogen-mpu',
    title: 'Drogen-MPU: Anlässe, Ablauf und Nachweise',
    slug: '/drogen-mpu/',
    excerpt: 'Was bei drogenbezogenen Fragestellungen fachlich getrennt betrachtet werden sollte.',
    primaryTopic: 'Drogen MPU Wissen',
    searchIntent: 'drug-related MPU concepts and evidence boundaries',
    ownerDomain: 'SHARED_WITH_DIFFERENT_INTENT',
    competingExistingPage: 'https://mpudeincoach.de/mpu-wegen-drogen (kommerzielle Vorbereitung und Orientierung)',
    uniqueValue: 'Substanzübergreifende Fachorientierung ohne Angebot oder Erfolgsversprechen; kommerzielle Vorbereitung bleibt auf der Hauptdomain.',
    pillar: 'Drogen MPU',
    pillarSlug: '/wissen/',
    sources: [SOURCES.fev13a, SOURCES.fev14Drugs, SOURCES.fev4a, SOURCES.bk5Drugs, SOURCES.bk5Ctu],
    reviewRequirements: ['MPU_FACHREVIEW', 'LEGAL_REVIEW', 'EDITORIAL_REVIEW', 'SOURCE_VERIFICATION'],
    reviewScope: 'Fachprüfung durch Drogen-/CTU-Kompetenz und rechtliche Aktualitätsprüfung der Cannabisgrenze vor Indexfreigabe erforderlich.',
    body: [
      { type: 'paragraph', text: 'Drogenbezogene MPU-Fragestellungen unterscheiden sich nach Substanz, Anlass, Konsumverlauf, Aktenlage und weiteren Auffälligkeiten. Deshalb ist es riskant, einzelne Regeln aus fremden Fällen zu übernehmen.' },
      { type: 'heading', id: 'anlass', title: 'Anlass und Akte zuerst klären' },
      { type: 'paragraph', text: 'Für eine fachliche Orientierung müssen mindestens Substanz, Zeitpunkt, dokumentierte Befunde, Verkehrsbezug, Vorgeschichte und die genaue behördliche Fragestellung auseinandergehalten werden.' },
      { type: 'heading', id: 'aufarbeitung', title: 'Konsumverlauf und Veränderung aufarbeiten' },
      { type: 'list', items: ['Entwicklung und Funktion des Konsums', 'Situationen und Auslöser', 'Folgen und frühere Verharmlosung', 'konkrete Veränderungsschritte', 'Schutzfaktoren und Rückfallvorsorge'] },
      { type: 'heading', id: 'nachweise', title: 'Nachweise sind mehr als ein Laborwert' },
      { type: 'paragraph', text: 'Laborbefunde müssen unter geregelten Bedingungen erhoben und im fachlichen Zusammenhang bewertet werden. Einzelne Werte, selbst gewählte Wartezeiten oder unklare Programme erlauben keine sichere Fallprognose.' },
      { type: 'important', title: 'Cannabis separat prüfen', text: 'Die FeV trennt Cannabisfälle von anderen Drogen- und Arzneimittelfragen: § 13a FeV regelt Eignungszweifel bei Cannabisproblematik, § 14 FeV die dort genannten Betäubungsmittel, Arzneimittel und anderen psychoaktiv wirkenden Stoffe. Daraus folgt keine pauschale Gleichbehandlung. Dieser Wissensartikel ersetzt keine aktuelle rechtliche oder fachliche Einzelfallbewertung.' },
    ],
    faq: [
      { question: 'Sind alle Drogen-MPUs gleich aufgebaut?', answer: 'Nein. Die Untersuchung ist anlassbezogen; außerdem regelt § 13a FeV Cannabisfragen getrennt von den in § 14 FeV behandelten anderen Drogen- und Arzneimittelfragen.', publicationState: 'REVIEW_REQUIRED' },
      { question: 'Beweist ein negativer Schnelltest ausreichende Abstinenz?', answer: 'Ein einzelner Schnelltest ist nicht mit einem formal verwertbaren Abstinenzbeleg gleichzusetzen. Anforderungen müssen fachlich und aktuell geprüft werden.', publicationState: 'REVIEW_REQUIRED' },
    ],
    relatedArticles: ['/abstinenznachweis/', '/mpu-ablauf/', '/faq/'],
    ctaTarget: 'FALLANALYSE',
    metaTitle: 'Drogen-MPU: Ablauf und Nachweise | MPU Wissen',
    metaDescription: 'Drogen-MPU als Wissensübersicht: Anlass, Konsumverlauf, Veränderung und Nachweise differenziert verstehen.',
    canonical: 'https://mpu-deincoach.de/drogen-mpu/',
  },
  {
    ...common,
    id: 'abstinenznachweis',
    title: 'Abstinenznachweis für die MPU: Überblick',
    slug: '/abstinenznachweis/',
    excerpt: 'Methoden, Kontrollbedingungen und typische Planungsfehler – ohne automatische Fallentscheidung.',
    primaryTopic: 'Abstinenznachweis MPU Wissen',
    searchIntent: 'CTU evidence integrity and documentation quality',
    ownerDomain: 'SHARED_WITH_DIFFERENT_INTENT',
    competingExistingPage: 'https://mpudeincoach.de/mpu-abstinenznachweis (fallbezogene Orientierung)',
    uniqueValue: 'CTU-Qualitäts- und Dokumentationswissen ohne Fallentscheidung, Lead-Rechner oder pauschale Dauerempfehlung.',
    pillar: 'Abstinenznachweis',
    pillarSlug: '/wissen/',
    sources: [SOURCES.bk5Ctu, SOURCES.fev4a],
    body: [
      { type: 'paragraph', text: 'Ein formal verwertbarer Abstinenzbeleg ist kein beliebiger Labortest. Anlage 4a FeV verlangt, dass die nach Stand von Wissenschaft und Technik erforderlichen Rahmenbedingungen der Abstinenzkontrolle gewährleistet sind. Ob ein Beleg erforderlich ist und welche Ausgestaltung im Einzelfall passt, bleibt fachlich zu prüfen.' },
      { type: 'heading', id: 'nachweiskette', title: 'Haar- und Urinbefunde in der Nachweiskette' },
      { type: 'paragraph', text: 'Haar- und Urinbefunde beruhen auf unterschiedlichem Probenmaterial und unterschiedlichen Entnahmeabläufen. Für die Belegqualität sind nicht nur das Ergebnis, sondern auch Identität, Entnahme, Untersuchungsstelle und vollständige Dokumentation relevant.' },
      { type: 'heading', id: 'qualitaet', title: 'Worauf es bei der Qualität ankommt' },
      { type: 'list', items: ['eindeutige Identitätskontrolle und dokumentierte Probenentnahme', 'geeignete und fachlich verantwortete Untersuchungsstelle', 'vollständige Unterlagen und nachvollziehbare Befundkette', 'rechtzeitige Klärung, bevor ein Programm begonnen wird'] },
      { type: 'heading', id: 'fehler', title: 'Typische Planungsfehler' },
      { type: 'list', items: ['mit einem Programm beginnen, bevor die Fragestellung geklärt ist', 'Einzeltests mit einem anerkennungsfähigen Programm verwechseln', 'pauschale Zeitangaben aus fremden Fällen übernehmen', 'Lücken oder Besonderheiten erst kurz vor dem MPU-Termin bemerken'] },
      { type: 'reflection', title: 'Vor dem Start klären', text: 'Welche Substanz oder welcher Anlass ist dokumentiert? Welche Unterlagen liegen vor? Wer verantwortet die Probenentnahme und Auswertung? Welche offenen Fragen müssen fachlich geprüft werden?' },
    ],
    faq: [
      { question: 'Kann ich einen Abstinenznachweis selbst mit Schnelltests führen?', answer: 'Selbsttests ersetzen keinen formal verwertbaren Abstinenzbeleg unter den erforderlichen Kontrollbedingungen.', publicationState: 'REVIEW_REQUIRED' },
      { question: 'Warum sind Haar- und Urinbefunde nicht pauschal austauschbar?', answer: 'Probenmaterial, Entnahmeablauf und dokumentierter Bezug unterscheiden sich. Ob ein Nachweis im Einzelfall passt, muss fachlich geprüft werden.', publicationState: 'REVIEW_REQUIRED' },
    ],
    relatedArticles: ['/alkohol-mpu/', '/drogen-mpu/', '/mpu-ablauf/'],
    ctaTarget: 'ABSTINENZ',
    metaTitle: 'Abstinenznachweis MPU: Methoden verstehen | MPU Wissen',
    metaDescription: 'Abstinenznachweis für die MPU: Haaranalyse, Urinkontrollprogramm, Qualitätsmerkmale und typische Fehler verständlich erklärt.',
    canonical: 'https://mpu-deincoach.de/abstinenznachweis/',
  },
  {
    ...common,
    id: 'mpu-begutachtungsstelle',
    title: 'MPU-Begutachtungsstelle wählen: Was du wissen solltest',
    slug: '/mpu-begutachtungsstelle/',
    excerpt: 'Amtliche Anerkennung, Auswahl, Aktenversand und praktische Kriterien verständlich erklärt.',
    primaryTopic: 'MPU Begutachtungsstelle wählen',
    searchIntent: 'informational / educational',
    ownerDomain: 'KNOWLEDGE',
    competingExistingPage: 'Kein gleichwertiger kommerzieller Eigentümer; Hauptdomain nur als Vorbereitungspfad.',
    uniqueValue: 'Neutraler, quellengestützter Leitfaden ohne Ranking oder Anbieterempfehlung.',
    pillar: 'Begutachtungsstellen',
    pillarSlug: '/wissen/',
    sources: [SOURCES.fev11, SOURCES.fev66, SOURCES.fev4a, SOURCES.fev14, SOURCES.bk5Foundations],
    reviewRequirements: ['MPU_FACHREVIEW', 'LEGAL_REVIEW', 'EDITORIAL_REVIEW', 'SOURCE_VERIFICATION'],
    reviewScope: 'Fachliche und rechtliche Prüfung der korrigierten Fassung abgeschlossen; Auswahl, Aktenweg und Trennungsregeln bleiben ohne Erfolgs- oder Fristversprechen.',
    publicationState: 'APPROVED_PUBLIC',
    schema: ['Article', 'BreadcrumbList', 'FAQPage'],
    body: [
      { type: 'paragraph', text: 'Eine Begutachtungsstelle für Fahreignung führt die medizinisch-psychologische Untersuchung durch und erstellt das Gutachten zur behördlichen Fragestellung. Für MPU-Gutachten kommen amtlich anerkannte Stellen in Betracht.' },
      { type: 'heading', id: 'was-ist-das', title: 'Was ist eine Begutachtungsstelle für Fahreignung?' },
      { type: 'paragraph', text: 'Träger und Stellen benötigen eine amtliche Anerkennung nach § 66 FeV. Die gesetzlichen Anforderungen betreffen unter anderem Personal, Ausstattung, Qualitätsmanagement, geeignete Testverfahren und die wirtschaftliche Unabhängigkeit der Gutachter vom Ergebnis.' },
      { type: 'heading', id: 'freie-wahl', title: 'Kann ich die Begutachtungsstelle wählen?' },
      { type: 'paragraph', text: '§ 11 Absatz 6 FeV sieht vor, dass die Behörde in Betracht kommende Stellen nennt und die betroffene Person mitteilt, welche Stelle sie beauftragt hat. Ob Besonderheiten im eigenen Verfahren bestehen, sollte anhand des behördlichen Schreibens geklärt werden.' },
      { type: 'heading', id: 'auswahl', title: 'Wie läuft die Auswahl praktisch ab?' },
      { type: 'list', items: ['behördliche Fragestellung und Frist prüfen', 'amtliche Anerkennung der konkreten Stelle verifizieren', 'Termin, Erreichbarkeit und benötigte Unterlagen erfragen', 'Stelle der Fahrerlaubnisbehörde fristgerecht mitteilen', 'schriftliche Angaben und Ansprechpartner aufbewahren'] },
      { type: 'heading', id: 'akte', title: 'Was passiert mit der Fahrerlaubnisakte?' },
      { type: 'paragraph', text: 'Nach § 11 Absatz 6 FeV übermittelt die Fahrerlaubnisbehörde der beauftragten Stelle die Fragestellung und die vollständigen Unterlagen, soweit sie unter Beachtung gesetzlicher Verwertungsverbote verwendet werden dürfen. Die FeV nennt außerdem ein Recht, die zu übersendenden Unterlagen einzusehen.' },
      { type: 'important', title: 'Rechtlicher Hinweis', text: 'Welche Unterlagen in deinem Verfahren verwertbar sind, wie Akteneinsicht praktisch beantragt wird und welche Frist gilt, kann diese allgemeine Seite nicht beurteilen. Das bleibt rechtlich reviewpflichtig.' },
      { type: 'heading', id: 'wechsel', title: 'Kann die Begutachtungsstelle gewechselt werden?' },
      { type: 'paragraph', text: 'Welche verfahrensbezogenen Folgen ein Wechsel im Einzelfall hat, lässt sich nicht pauschal bestimmen. Kläre einen geplanten Wechsel deshalb vorab mit der Fahrerlaubnisbehörde und den beteiligten Stellen; aus dieser allgemeinen Information folgen weder ein uneingeschränktes Wechselrecht noch bestimmte Fristwirkungen.' },
      { type: 'heading', id: 'unterschiede', title: 'Gibt es Unterschiede zwischen Begutachtungsstellen?' },
      { type: 'paragraph', text: 'Amtlich anerkannte Stellen müssen dieselben rechtlichen und fachlichen Grundanforderungen erfüllen. Praktische Unterschiede kann es etwa bei Standorten, Terminorganisation, Kommunikation, Barrierefreiheit, angebotenen Sprachen und Kosten geben. Ein seriöser Vergleich bewertet solche überprüfbaren Kriterien und verspricht kein günstigeres Ergebnis.' },
      { type: 'heading', id: 'logistik', title: 'Entfernung und Logistik realistisch planen' },
      { type: 'list', items: ['Anreise und Puffer am Untersuchungstag', 'Barrierefreiheit oder notwendige Unterstützung', 'Umgang mit Dolmetschleistungen vorab klären', 'Fristen, Zahlungsbedingungen und benötigte Originalunterlagen', 'Erreichbarkeit bei Rückfragen'] },
      { type: 'heading', id: 'mythen', title: 'Häufige Missverständnisse' },
      { type: 'list', items: ['„Eine bestimmte Stelle garantiert bessere Chancen.“ – Amtlich anerkannte Stellen unterliegen gemeinsamen rechtlichen und fachlichen Anforderungen; eine Erfolgsgarantie gibt es nicht.', '„Die Begutachtungsstelle ordnet die MPU an.“ – Die Fragestellung kommt von der Fahrerlaubnisbehörde.', '„Weit weg ist automatisch besser.“ – Entfernung ist vor allem eine praktische, keine fachliche Qualitätskennzahl.', '„Vorbereitung und Begutachtung sind dasselbe.“ – Anlage 14 FeV untersagt einem Träger von Begutachtungsstellen unter den dort geregelten Anerkennungsvoraussetzungen zugleich bestimmte Vorbereitungsmaßnahmen; zusätzlich dürfen nach Anlage 4a FeV Personen mit den dort beschriebenen Verbindungen oder eigenen Angeboten nicht untersuchen oder begutachten.'] },
    ],
    faq: [
      { question: 'Muss eine MPU-Stelle amtlich anerkannt sein?', answer: 'Für das medizinisch-psychologische Gutachten nach § 11 Absatz 3 FeV ist eine amtlich anerkannte Begutachtungsstelle für Fahreignung vorgesehen.', publicationState: 'PUBLIC_APPROVED' },
      { question: 'Sendet die Führerscheinstelle die Akte direkt an mich?', answer: '§ 11 Absatz 6 FeV beschreibt die Übermittlung der verwendbaren Unterlagen an die beauftragte Untersuchungsstelle und ein Einsichtsrecht in die zu übersendenden Unterlagen. Der konkrete Ablauf ist mit der zuständigen Behörde zu klären.', publicationState: 'PUBLIC_APPROVED' },
      { question: 'Ist die nächstgelegene Stelle immer die beste Wahl?', answer: 'Nicht zwingend. Erreichbarkeit ist wichtig; zusätzlich können Terminorganisation, Barrierefreiheit, Kommunikation, Sprache und transparente Kosten eine Rolle spielen.', publicationState: 'PUBLIC_APPROVED' },
      { question: 'Kann eine Begutachtungsstelle gleichzeitig meine Vorbereitung verkaufen?', answer: 'Für Träger von Begutachtungsstellen gelten die Anerkennungs- und Trennungsanforderungen aus Anlage 14 FeV. Außerdem dürfen untersuchende oder begutachtende Personen nach Anlage 4a FeV nicht zugleich die dort beschriebenen Vorbereitungsmaßnahmen anbieten oder mit entsprechenden Anbietern vertraglich verbunden sein.', publicationState: 'PUBLIC_APPROVED' },
    ],
    relatedArticles: ['/mpu-ablauf/', '/faq/', '/mpu-kosten/'],
    ctaTarget: 'MPU_VORBEREITUNG',
    metaTitle: 'MPU-Begutachtungsstelle wählen | MPU Wissen',
    metaDescription: 'MPU-Begutachtungsstelle wählen: amtliche Anerkennung, Auswahl, Fahrerlaubnisakte, Wechsel, Unterschiede und praktische Kriterien.',
    canonical: 'https://mpu-deincoach.de/mpu-begutachtungsstelle/',
  },
];

export const articleBySlug = (slug: string) => ARTICLES.find((article) => article.slug === slug);
