import { EDITORIAL_TEAM } from '../config/site';
import type { Article } from './model';
import { SOURCES } from './sources';

const common = {
  author: EDITORIAL_TEAM,
  reviewer: null,
  reviewScope: 'Fachliche und gegebenenfalls rechtliche Prüfung vor Indexfreigabe erforderlich.',
  updatedAt: '2026-09-02',
  nextReviewAt: '2027-03-02',
  indexability: 'noindex' as const,
  status: 'review_required' as const,
  schema: ['Article', 'BreadcrumbList'] as Article['schema'],
};

export const ARTICLES: Article[] = [
  {
    ...common,
    id: 'mpu-ablauf',
    title: 'MPU-Ablauf: Schritte, Untersuchung und Gutachten',
    slug: '/mpu-ablauf/',
    excerpt: 'Eine ruhige Orientierung vom behördlichen Schreiben bis zum Gutachten – ohne starre Zeitversprechen.',
    primaryTopic: 'MPU Ablauf',
    searchIntent: 'informational / educational',
    ownerDomain: 'SHARED_WITH_DIFFERENT_INTENT',
    competingExistingPage: 'https://mpudeincoach.de/ (kurzer, fallanalyseorientierter Ablauf)',
    uniqueValue: 'Der Wissenshub erklärt Rollen, Unterlagen, Untersuchungsteile und Übergänge in redaktioneller Tiefe.',
    pillar: 'MPU Ablauf',
    pillarSlug: '/wissen/',
    sources: [SOURCES.fev11, SOURCES.fev4a, SOURCES.bk5Foundations],
    body: [
      { type: 'paragraph', text: 'Der konkrete Weg zur MPU ist nicht bei allen Menschen gleich. Anlass, behördliche Fragestellung, Aktenlage und erforderliche Unterlagen beeinflussen die einzelnen Schritte. Diese Übersicht zeigt deshalb eine Struktur – keinen verbindlichen persönlichen Fahrplan.' },
      { type: 'important', title: 'Wichtig', text: 'Fristen stehen im behördlichen Schreiben. Verlasse dich bei Fristfragen nicht auf allgemeine Internetangaben, sondern kläre dein eigenes Schreiben rechtzeitig mit der zuständigen Stelle oder fachkundiger rechtlicher Beratung.' },
      { type: 'heading', id: 'anordnung', title: '1. Die behördliche Fragestellung verstehen' },
      { type: 'paragraph', text: 'Die Fahrerlaubnisbehörde legt fest, welche Eignungsfrage durch ein Gutachten geklärt werden soll. Diese Fragestellung begrenzt den fachlichen Rahmen der Untersuchung. Sie ist deshalb ein zentraler Ausgangspunkt für die weitere Orientierung.' },
      { type: 'list', items: ['Schreiben und genannte Frist vollständig lesen', 'Fragestellung wörtlich festhalten', 'Hinweise auf einzureichende Unterlagen markieren', 'Unklare rechtliche Folgen nicht selbst interpretieren'] },
      { type: 'heading', id: 'stelle', title: '2. Eine amtlich anerkannte Begutachtungsstelle beauftragen' },
      { type: 'paragraph', text: 'Die Untersuchung findet bei einer amtlich anerkannten Begutachtungsstelle für Fahreignung statt. Nach § 11 Absatz 6 FeV teilt die betroffene Person der Behörde mit, welche in Betracht kommende Stelle beauftragt wurde; anschließend übermittelt die Behörde die verwendbaren Unterlagen und ihre Fragestellung.' },
      { type: 'heading', id: 'vorbereitung', title: '3. Akte, Vorgeschichte und Veränderung aufarbeiten' },
      { type: 'paragraph', text: 'Eine sinnvolle Vorbereitung trennt Sachverhalte, persönliche Entwicklung und noch offene Nachweise. Entscheidend ist nicht das Auswendiglernen fertiger Antworten, sondern eine nachvollziehbare Auseinandersetzung mit dem eigenen Verhalten und den daraus gezogenen Konsequenzen.' },
      { type: 'heading', id: 'untersuchung', title: '4. Die Untersuchung' },
      { type: 'paragraph', text: 'Je nach Fragestellung können medizinische, psychologische und leistungsbezogene Untersuchungsteile relevant sein. Die FeV verlangt eine anlassbezogene Untersuchung nach anerkannten wissenschaftlichen Grundsätzen.' },
      { type: 'heading', id: 'gutachten', title: '5. Das Gutachten und die nächsten Schritte' },
      { type: 'paragraph', text: 'Das Gutachten beantwortet die behördliche Fragestellung. Welche Konsequenzen sich daraus im Einzelfall ergeben und wie mit einem Ergebnis umzugehen ist, ist eine rechtlich und fachlich sensible Frage. Diese Seite ersetzt keine Einzelfallprüfung.' },
    ],
    faq: [
      { question: 'Wie lange dauert der gesamte MPU-Ablauf?', answer: 'Eine pauschale Dauer ist nicht seriös: Fristen, Aktenversand, Terminverfügbarkeit, mögliche Nachweise und der individuelle Aufarbeitungsstand unterscheiden sich.' },
      { question: 'Besteht jede MPU aus denselben Teilen?', answer: 'Die Untersuchung folgt fachlichen Grundsätzen, bleibt aber anlassbezogen. Welche Bestandteile und Befunde im konkreten Fall bedeutsam sind, hängt von der behördlichen Fragestellung ab.' },
    ],
    relatedArticles: ['/mpu-begutachtungsstelle/', '/abstinenznachweis/', '/faq/'],
    ctaTarget: 'FALLANALYSE',
    metaTitle: 'MPU-Ablauf verständlich erklärt | MPU Wissen',
    metaDescription: 'MPU-Ablauf verständlich erklärt: Fragestellung, Begutachtungsstelle, Untersuchung und Gutachten – quellenorientiert und ohne starre Fristen.',
    canonical: 'https://mpu-deincoach.de/mpu-ablauf/',
  },
  {
    ...common,
    id: 'mpu-kosten',
    title: 'MPU-Kosten: Bestandteile und Einflussfaktoren',
    slug: '/mpu-kosten/',
    excerpt: 'Welche Kostenblöcke vorkommen können und warum ein einziger Pauschalbetrag häufig in die Irre führt.',
    primaryTopic: 'MPU Kosten',
    searchIntent: 'informational / comparative',
    ownerDomain: 'SHARED_WITH_DIFFERENT_INTENT',
    competingExistingPage: 'https://mpudeincoach.de/mpu-kosten (Service- und Vorbereitungskosten)',
    uniqueValue: 'Neutrale Kostenarchitektur ohne Paketpreise, Angebotsvergleich oder Verkaufsabsicht.',
    pillar: 'MPU Kosten',
    pillarSlug: '/wissen/',
    sources: [SOURCES.fev11, SOURCES.bk5Foundations],
    body: [
      { type: 'paragraph', text: 'Zu den Gesamtkosten rund um eine MPU können mehrere voneinander unabhängige Positionen gehören. Ein einzelner Betrag ohne Kontext sagt daher wenig aus. Aktuelle Preise müssen direkt bei den jeweils beauftragten Stellen geprüft werden.' },
      { type: 'heading', id: 'kostenbloecke', title: 'Mögliche Kostenblöcke' },
      { type: 'list', items: ['Gebühren und Auslagen im Fahrerlaubnisverfahren', 'Entgelt der Begutachtungsstelle', 'gegebenenfalls Kosten für Labor- oder Abstinenznachweise', 'gegebenenfalls Übersetzungs- oder Dolmetschleistungen', 'frei gewählte Vorbereitung oder fachliche Beratung', 'Anfahrt, Übernachtung und Dokumentenbeschaffung'] },
      { type: 'heading', id: 'vergleich', title: 'Preise sinnvoll vergleichen' },
      { type: 'paragraph', text: 'Vergleiche nicht nur Endbeträge. Prüfe, welche Leistungen enthalten sind, ob zusätzliche Befunde benötigt werden können und ob die Angaben aktuell, schriftlich und für deine Fragestellung passend sind.' },
      { type: 'callout', title: 'Keine Preisfreigabe', text: 'Diese Fassung veröffentlicht bewusst keine konkreten Preiszahlen. Kostenangaben sind zeitabhängig und müssen vor Veröffentlichung redaktionell sowie bei den jeweiligen Stellen geprüft werden.' },
    ],
    faq: [
      { question: 'Gibt es einen einheitlichen Preis für jede MPU?', answer: 'Nein. Anlass, Umfang, Begutachtungsstelle, mögliche Nachweise und weitere Verfahrenskosten können die Gesamtsumme beeinflussen.' },
      { question: 'Sind Vorbereitungskosten Teil des MPU-Entgelts?', answer: 'Vorbereitung und Begutachtung sind getrennte Leistungen. Welche freiwillige Vorbereitung gewählt wird, ist eine eigene Entscheidung.' },
    ],
    relatedArticles: ['/mpu-ablauf/', '/abstinenznachweis/', '/mpu-begutachtungsstelle/'],
    ctaTarget: 'FALLANALYSE',
    metaTitle: 'MPU-Kosten: Bestandteile verstehen | MPU Wissen',
    metaDescription: 'MPU-Kosten neutral einordnen: mögliche Kostenblöcke, Einflussfaktoren und sinnvolle Fragen beim Vergleich – ohne veraltete Pauschalpreise.',
    canonical: 'https://mpu-deincoach.de/mpu-kosten/',
  },
  {
    ...common,
    id: 'alkohol-mpu',
    title: 'Alkohol-MPU: Grundlagen und Wissensübersicht',
    slug: '/alkohol-mpu/',
    excerpt: 'Eine fachliche Landkarte zu Anlass, Konsumgeschichte, Veränderung und Nachweisen.',
    primaryTopic: 'Alkohol MPU Wissen',
    searchIntent: 'informational / educational',
    ownerDomain: 'SHARED_WITH_DIFFERENT_INTENT',
    competingExistingPage: 'https://mpudeincoach.de/mpu-wegen-alkohol (kommerzielle Vorbereitung)',
    uniqueValue: 'Begriffliche und fachliche Orientierung statt Fallanalyse, Angebot oder Erfolgsversprechen.',
    pillar: 'Alkohol MPU',
    pillarSlug: '/wissen/',
    sources: [SOURCES.bk5Alcohol, SOURCES.fev4a, SOURCES.bastGuidelines],
    body: [
      { type: 'paragraph', text: 'Bei einer Alkohol-MPU geht es nicht um eine isolierte Musterantwort. Fachlich betrachtet werden Anlass, Entwicklung des Konsums, persönliche Risikofaktoren, die Auseinandersetzung mit dem Verhalten und die Stabilität der Veränderung.' },
      { type: 'heading', id: 'konsumgeschichte', title: 'Die eigene Konsumgeschichte einordnen' },
      { type: 'paragraph', text: 'Wichtig ist eine zeitlich nachvollziehbare Darstellung: Wie hat sich der Konsum entwickelt, in welchen Situationen wurde getrunken und welche Folgen wurden lange unterschätzt? Eine ehrliche Rekonstruktion ist etwas anderes als eine nachträglich geglättete Geschichte.' },
      { type: 'heading', id: 'veraenderung', title: 'Veränderung muss zum früheren Risiko passen' },
      { type: 'paragraph', text: 'Tragfähige Veränderungen betreffen nicht nur den Alkoholkonsum selbst. Häufig gehören neue Entscheidungen, andere Routinen, ein veränderter Umgang mit Belastungen und ein konkreter Plan für Risikosituationen dazu.' },
      { type: 'heading', id: 'abstinenz', title: 'Abstinenz und kontrollierter Umgang nicht pauschal entscheiden' },
      { type: 'important', title: 'Einzelfallprüfung', text: 'Ob Abstinenz, ein kontrollierter Umgang oder ein anderer fachlicher Weg tragfähig ist, darf nicht anhand eines einzelnen Werts oder einer allgemeinen Internetregel entschieden werden. Die Einordnung bleibt fachlich reviewpflichtig.' },
      { type: 'heading', id: 'nachweise', title: 'Nachweise früh und passend klären' },
      { type: 'paragraph', text: 'Wenn Nachweise relevant sind, müssen Methode, Zeitraum und formale Qualität zum fachlichen Bedarf passen. Nachträglich lässt sich ein ungeeignetes oder lückenhaftes Vorgehen nicht immer korrigieren.' },
    ],
    faq: [
      { question: 'Braucht jede Alkohol-MPU einen Abstinenznachweis?', answer: 'Nein, eine pauschale Aussage ist fachlich nicht vertretbar. Anlass, Konsummuster, Vorgeschichte, Veränderungsweg und Aktenlage müssen zusammen geprüft werden.' },
      { question: 'Reicht es, seit dem Vorfall weniger zu trinken?', answer: 'Eine bloße Behauptung reicht nicht. Entscheidend ist, ob die Veränderung nachvollziehbar, stabil und zum früheren Risiko passend aufgearbeitet wurde.' },
    ],
    relatedArticles: ['/abstinenznachweis/', '/mpu-ablauf/', '/faq/'],
    ctaTarget: 'ALKOHOL',
    metaTitle: 'Alkohol-MPU: Grundlagen verstehen | MPU Wissen',
    metaDescription: 'Alkohol-MPU verständlich einordnen: Konsumgeschichte, Veränderung, Risikoverständnis und Nachweise – ohne pauschale Versprechen.',
    canonical: 'https://mpu-deincoach.de/alkohol-mpu/',
  },
  {
    ...common,
    id: 'drogen-mpu',
    title: 'Drogen-MPU: Anlässe, Ablauf und Nachweise',
    slug: '/drogen-mpu/',
    excerpt: 'Was bei drogenbezogenen Fragestellungen fachlich getrennt betrachtet werden sollte.',
    primaryTopic: 'Drogen MPU Wissen',
    searchIntent: 'informational / educational',
    ownerDomain: 'KNOWLEDGE',
    competingExistingPage: 'https://mpudeincoach.de/mpu-wegen-cannabis (Cannabis-Vorbereitung)',
    uniqueValue: 'Substanzübergreifende Fachorientierung für nicht-kommerzielle Wissensfragen; Cannabis bleibt bewusst getrennt.',
    pillar: 'Drogen MPU',
    pillarSlug: '/wissen/',
    sources: [SOURCES.bk5Drugs, SOURCES.bk5Ctu, SOURCES.fev4a],
    body: [
      { type: 'paragraph', text: 'Drogenbezogene MPU-Fragestellungen unterscheiden sich nach Substanz, Anlass, Konsumverlauf, Aktenlage und weiteren Auffälligkeiten. Deshalb ist es riskant, einzelne Regeln aus fremden Fällen zu übernehmen.' },
      { type: 'heading', id: 'anlass', title: 'Anlass und Akte zuerst klären' },
      { type: 'paragraph', text: 'Für eine fachliche Orientierung müssen mindestens Substanz, Zeitpunkt, dokumentierte Befunde, Verkehrsbezug, Vorgeschichte und die genaue behördliche Fragestellung auseinandergehalten werden.' },
      { type: 'heading', id: 'aufarbeitung', title: 'Konsumverlauf und Veränderung aufarbeiten' },
      { type: 'list', items: ['Entwicklung und Funktion des Konsums', 'Situationen und Auslöser', 'Folgen und frühere Verharmlosung', 'konkrete Veränderungsschritte', 'Schutzfaktoren und Rückfallvorsorge'] },
      { type: 'heading', id: 'nachweise', title: 'Nachweise sind mehr als ein Laborwert' },
      { type: 'paragraph', text: 'Laborbefunde müssen unter geregelten Bedingungen erhoben und im fachlichen Zusammenhang bewertet werden. Einzelne Werte, selbst gewählte Wartezeiten oder unklare Programme erlauben keine sichere Fallprognose.' },
      { type: 'important', title: 'Cannabis separat prüfen', text: 'Cannabisfragen überschneiden sich mit aktueller Gesetzgebung und dem kommerziellen Cannabis-Angebot auf mpudeincoach.de. Dieser Wissensartikel ersetzt keine aktuelle rechtliche oder fachliche Einzelfallbewertung.' },
    ],
    faq: [
      { question: 'Sind alle Drogen-MPUs gleich aufgebaut?', answer: 'Nein. Die Untersuchung ist anlassbezogen; Substanz, Konsumverlauf, Befunde, Aktenlage und Fragestellung können unterschiedliche Schwerpunkte setzen.' },
      { question: 'Beweist ein negativer Schnelltest ausreichende Abstinenz?', answer: 'Ein einzelner Schnelltest ist nicht mit einem formal geeigneten Abstinenznachweis gleichzusetzen. Anforderungen müssen fachlich und aktuell geprüft werden.' },
    ],
    relatedArticles: ['/abstinenznachweis/', '/mpu-ablauf/', '/faq/'],
    ctaTarget: 'FALLANALYSE',
    metaTitle: 'Drogen-MPU: Ablauf und Nachweise | MPU Wissen',
    metaDescription: 'Drogen-MPU als Wissensübersicht: Anlass, Konsumverlauf, Veränderung und Nachweise differenziert verstehen.',
    canonical: 'https://mpu-deincoach.de/drogen-mpu/',
  },
  {
    ...common,
    id: 'abstinenznachweis',
    title: 'Abstinenznachweis für die MPU: Überblick',
    slug: '/abstinenznachweis/',
    excerpt: 'Methoden, Kontrollbedingungen und typische Planungsfehler – ohne automatische Fallentscheidung.',
    primaryTopic: 'Abstinenznachweis MPU Wissen',
    searchIntent: 'informational / educational',
    ownerDomain: 'SHARED_WITH_DIFFERENT_INTENT',
    competingExistingPage: 'https://mpudeincoach.de/abstinenznachweis (fallbezogene Orientierung)',
    uniqueValue: 'Methoden- und Qualitätswissen ohne Lead-Rechner oder pauschale Dauerempfehlung.',
    pillar: 'Abstinenznachweis',
    pillarSlug: '/wissen/',
    sources: [SOURCES.bk5Ctu, SOURCES.fev4a],
    body: [
      { type: 'paragraph', text: 'Ein Abstinenznachweis ist kein beliebiger Labortest. Er dokumentiert Kontrollen unter fachlich festgelegten Bedingungen. Ob ein Nachweis erforderlich ist, welche Methode passt und welcher Zeitraum relevant ist, bleibt eine Einzelfallfrage.' },
      { type: 'heading', id: 'methoden', title: 'Haaranalyse und Urinkontrollprogramm' },
      { type: 'paragraph', text: 'Beide Wege unterscheiden sich in Probenmaterial, Planbarkeit, Rückblick und organisatorischem Ablauf. Nicht jede Methode passt zu jeder Substanz oder persönlichen Situation.' },
      { type: 'heading', id: 'qualitaet', title: 'Worauf es bei der Qualität ankommt' },
      { type: 'list', items: ['eindeutige Identitätskontrolle und dokumentierte Probenentnahme', 'geeignete und fachlich verantwortete Untersuchungsstelle', 'vollständige Unterlagen und nachvollziehbare Befundkette', 'rechtzeitige Klärung, bevor ein Programm begonnen wird'] },
      { type: 'heading', id: 'fehler', title: 'Typische Planungsfehler' },
      { type: 'list', items: ['mit einem Programm beginnen, bevor die Fragestellung geklärt ist', 'Einzeltests mit einem anerkennungsfähigen Programm verwechseln', 'pauschale Zeitangaben aus fremden Fällen übernehmen', 'Lücken oder Besonderheiten erst kurz vor dem MPU-Termin bemerken'] },
      { type: 'reflection', title: 'Vor dem Start klären', text: 'Welche Substanz oder welcher Anlass ist dokumentiert? Welche Unterlagen liegen vor? Wer verantwortet die Probenentnahme und Auswertung? Welche offenen Fragen müssen fachlich geprüft werden?' },
    ],
    faq: [
      { question: 'Kann ich einen Abstinenznachweis selbst mit Schnelltests führen?', answer: 'Selbsttests ersetzen kein fachlich geregeltes und dokumentiertes Kontrollprogramm.' },
      { question: 'Welche Methode ist besser: Haar oder Urin?', answer: 'Das lässt sich nicht allgemein beantworten. Substanz, Zeitraum, persönliche Voraussetzungen und formale Anforderungen müssen zusammen betrachtet werden.' },
    ],
    relatedArticles: ['/alkohol-mpu/', '/drogen-mpu/', '/mpu-ablauf/'],
    ctaTarget: 'ABSTINENZ',
    metaTitle: 'Abstinenznachweis MPU: Methoden verstehen | MPU Wissen',
    metaDescription: 'Abstinenznachweis für die MPU: Haaranalyse, Urinkontrollprogramm, Qualitätsmerkmale und typische Fehler verständlich erklärt.',
    canonical: 'https://mpu-deincoach.de/abstinenznachweis/',
  },
  {
    ...common,
    id: 'mpu-begutachtungsstelle',
    title: 'MPU-Begutachtungsstelle wählen: Was du wissen solltest',
    slug: '/mpu-begutachtungsstelle/',
    excerpt: 'Amtliche Anerkennung, Auswahl, Aktenversand und praktische Kriterien verständlich erklärt.',
    primaryTopic: 'MPU Begutachtungsstelle wählen',
    searchIntent: 'informational / educational',
    ownerDomain: 'KNOWLEDGE',
    competingExistingPage: 'Kein gleichwertiger kommerzieller Eigentümer; Hauptdomain nur als Vorbereitungspfad.',
    uniqueValue: 'Neutraler, quellengestützter Leitfaden ohne Ranking oder Anbieterempfehlung.',
    pillar: 'Begutachtungsstellen',
    pillarSlug: '/wissen/',
    sources: [SOURCES.fev11, SOURCES.fev66, SOURCES.fev4a, SOURCES.fev14, SOURCES.bk5Foundations],
    body: [
      { type: 'paragraph', text: 'Eine Begutachtungsstelle für Fahreignung führt die medizinisch-psychologische Untersuchung durch und erstellt das Gutachten zur behördlichen Fragestellung. Für MPU-Gutachten kommen amtlich anerkannte Stellen in Betracht.' },
      { type: 'heading', id: 'was-ist-das', title: 'Was ist eine Begutachtungsstelle für Fahreignung?' },
      { type: 'paragraph', text: 'Träger und Stellen benötigen eine amtliche Anerkennung nach § 66 FeV. Die gesetzlichen Anforderungen betreffen unter anderem Personal, Ausstattung, Qualitätsmanagement, geeignete Testverfahren und die wirtschaftliche Unabhängigkeit der Gutachter vom Ergebnis.' },
      { type: 'heading', id: 'freie-wahl', title: 'Kann ich die Begutachtungsstelle wählen?' },
      { type: 'paragraph', text: '§ 11 Absatz 6 FeV sieht vor, dass die Behörde in Betracht kommende Stellen nennt und die betroffene Person mitteilt, welche Stelle sie beauftragt hat. Ob Besonderheiten im eigenen Verfahren bestehen, sollte anhand des behördlichen Schreibens geklärt werden.' },
      { type: 'heading', id: 'auswahl', title: 'Wie läuft die Auswahl praktisch ab?' },
      { type: 'list', items: ['behördliche Fragestellung und Frist prüfen', 'amtliche Anerkennung der konkreten Stelle verifizieren', 'Termin, Erreichbarkeit und benötigte Unterlagen erfragen', 'Stelle der Fahrerlaubnisbehörde fristgerecht mitteilen', 'schriftliche Angaben und Ansprechpartner aufbewahren'] },
      { type: 'heading', id: 'akte', title: 'Was passiert mit der Fahrerlaubnisakte?' },
      { type: 'paragraph', text: 'Nach § 11 Absatz 6 FeV übermittelt die Fahrerlaubnisbehörde der beauftragten Stelle die Fragestellung und die vollständigen Unterlagen, soweit sie unter Beachtung gesetzlicher Verwertungsverbote verwendet werden dürfen. Die FeV nennt außerdem ein Recht, die zu übersendenden Unterlagen einzusehen.' },
      { type: 'important', title: 'Rechtlicher Hinweis', text: 'Welche Unterlagen in deinem Verfahren verwertbar sind, wie Akteneinsicht praktisch beantragt wird und welche Frist gilt, kann diese allgemeine Seite nicht beurteilen. Das bleibt rechtlich reviewpflichtig.' },
      { type: 'heading', id: 'wechsel', title: 'Kann die Begutachtungsstelle gewechselt werden?' },
      { type: 'paragraph', text: 'Ein Wechsel kann Auswirkungen auf Auftrag, Aktenversand, Termin und Frist haben. Ohne Kenntnis des konkreten Verfahrens wäre eine pauschale Anleitung unseriös. Kläre einen geplanten Wechsel zuerst mit der Fahrerlaubnisbehörde und den beteiligten Stellen.' },
      { type: 'heading', id: 'unterschiede', title: 'Gibt es Unterschiede zwischen Begutachtungsstellen?' },
      { type: 'paragraph', text: 'Amtlich anerkannte Stellen müssen dieselben rechtlichen und fachlichen Grundanforderungen erfüllen. Praktische Unterschiede kann es etwa bei Standorten, Terminorganisation, Kommunikation, Barrierefreiheit, angebotenen Sprachen und Kosten geben. Ein seriöser Vergleich bewertet solche überprüfbaren Kriterien und verspricht kein günstigeres Ergebnis.' },
      { type: 'heading', id: 'logistik', title: 'Entfernung und Logistik realistisch planen' },
      { type: 'list', items: ['Anreise und Puffer am Untersuchungstag', 'Barrierefreiheit oder notwendige Unterstützung', 'Umgang mit Dolmetschleistungen vorab klären', 'Fristen, Zahlungsbedingungen und benötigte Originalunterlagen', 'Erreichbarkeit bei Rückfragen'] },
      { type: 'heading', id: 'mythen', title: 'Häufige Missverständnisse' },
      { type: 'list', items: ['„Eine bestimmte Stelle lässt mehr Menschen bestehen.“ – Dafür liefert ein Anbieter-Ranking keine belastbare Grundlage.', '„Die Begutachtungsstelle ordnet die MPU an.“ – Die Fragestellung kommt von der Fahrerlaubnisbehörde.', '„Weit weg ist automatisch besser.“ – Entfernung ist vor allem eine praktische, keine fachliche Qualitätskennzahl.', '„Vorbereitung und Begutachtung sind dasselbe.“ – Die FeV verlangt eine organisatorische Trennung bestimmter Rollen.'] },
    ],
    faq: [
      { question: 'Muss eine MPU-Stelle amtlich anerkannt sein?', answer: 'Für das medizinisch-psychologische Gutachten nach § 11 Absatz 3 FeV ist eine amtlich anerkannte Begutachtungsstelle für Fahreignung vorgesehen.' },
      { question: 'Sendet die Führerscheinstelle die Akte direkt an mich?', answer: '§ 11 Absatz 6 FeV beschreibt die Übermittlung der verwendbaren Unterlagen an die beauftragte Untersuchungsstelle und ein Einsichtsrecht in die zu übersendenden Unterlagen. Der konkrete Ablauf ist mit der zuständigen Behörde zu klären.' },
      { question: 'Ist die nächstgelegene Stelle immer die beste Wahl?', answer: 'Nicht zwingend. Erreichbarkeit ist wichtig; zusätzlich können Terminorganisation, Barrierefreiheit, Kommunikation, Sprache und transparente Kosten eine Rolle spielen.' },
      { question: 'Kann eine Begutachtungsstelle gleichzeitig meine Vorbereitung verkaufen?', answer: 'Anlage 14 FeV enthält Trennungs- und Unabhängigkeitsanforderungen. Prüfe Angebote und Rollen sorgfältig; eine individuelle rechtliche Bewertung ersetzt diese Information nicht.' },
    ],
    relatedArticles: ['/mpu-ablauf/', '/faq/', '/mpu-kosten/'],
    ctaTarget: 'MPU_VORBEREITUNG',
    metaTitle: 'MPU-Begutachtungsstelle wählen | MPU Wissen',
    metaDescription: 'MPU-Begutachtungsstelle wählen: amtliche Anerkennung, Auswahl, Fahrerlaubnisakte, Wechsel, Unterschiede und praktische Kriterien.',
    canonical: 'https://mpu-deincoach.de/mpu-begutachtungsstelle/',
  },
];

export const articleBySlug = (slug: string) => ARTICLES.find((article) => article.slug === slug);
